apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflared
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mohamedkaba4/Kubernetes-DockingStation.git
    targetRevision: main
    path: platform/cloudflared
  destination:
    server: https://kubernetes.default.svc
    namespace: cloudflare
  syncPolicy:
    automated:
      enabled: true
      prune: false
      selfHeal: true
